### ISSUE TITLE
Function for CREATE UNIQUE

### ISSUE THREAD

**Issue by tkvogt** [asilvestre/haskell-neo4j-rest-client#21]
Do you think there should be function to avoid duplicated nodes? Or can this already be done somehow?

**Comment by asilvestre** [comment]
Hi,

This feature is not available in the CRUD section of the API (i.e. [createNode](http://hackage.haskell.org/package/haskell-neo4j-client-0.3.2.0/docs/Database-Neo4j.html#v:createNode) and so on). This is so because these operations map directly to operations offered by Neo4j's REST API and as far as I know they don't offer CREATE UNIQUE for nodes (otherwise please let me know).

However, CREATE UNIQUE is available in Neo4j's Cypher query language, with this driver you can send cypher queries using these [calls](http://hackage.haskell.org/package/haskell-neo4j-client-0.3.2.0/docs/Database-Neo4j-Transactional-Cypher.html)

**Comment by tkvogt** [comment]
OK. Lets hope that this is reasonably fast. I am currently trying to store the gitgub event stream into Neo4j. 46 GB from January to September this year.
